car = "benz"
print("\nIs car =='benz'? I predict True.")
print(car == "benz")

print("Is car == 'audi'? I predict False.")
print(car == "audi")

"bmw", "audi", "toyota", "subaru"

car = "bmw"
print("\nIs car =='bmw'? I predict True.")
print(car == "bmw")

print("Is car == 'audi'? I predict False.")
print(car == "audi")

car = "audi"

print("\nIs car == 'audi'? I predict True.")
print(car == "audi")

print("Is car == 'bmw'? I predict False.")
print(car == "bmw")

car = "toyota"

print("\nIs car == 'toyota'? I predict True.")
print(car == "toyota")

print("Is car =='audi'? I predict False.")
print(car == "audi")

car = "subaru"
print("\nIs car =='subaru'? I predict True.")
print(car == "subaru")

print("Is car == 'audi'? I predict True.")
print(car == "audi")
